### ISSUE TITLE
Unexisting file causes error

### ISSUE THREAD

**Issue by stefdaems** [scottcorgan/file-exists#7]
[2017-03-07 16:58:38.978] [ERROR] ./index.js - UNCAUGHT ERROR TypeError: Cannot read property 'isFile' of undefined
    at fs.stat (C:\XXX\XXX\XXProject\node_modules\file-exists\index.js:10:71)
    at FSReqWrap.oncomplete (fs.js:117:15) (10)

Whenever a file is not existing, we run into an error.

Seen on version 3.0.1
Not seen on version 2.0.0

**Comment by scottcorgan** [comment]
Fixed and released as `3.0.2`. Thanks for the heads up!

**Comment by perry-mitchell** [comment]
I'm still receiving this error on `3.0.2`. I've placed a comment in the file exists func:

```js
function fileExits (filepath, options, done = function () {}) {
  if (typeof options === 'function') {
    done = options
    options = {}
  }

  fs.stat(fullPath(filepath, options), (err, stats) => {
    if (err) {
      console.log("ERRRRR", err);
      return done(err)
    }

    done(null, stats.isFile())
  })
}
```

And when I'm calling it I get an error instead of expected `false` output:

```
ERRRRR { Error: ENOENT: no such file or directory, stat '/home/perry/Temp/fileseg/test/empty.fileseg'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/perry/Temp/fileseg/test/empty.fileseg' }
```

The directory `/home/perry/Temp/fileseg/test/` exists:

![image](https://cloud.githubusercontent.com/assets/3869469/26573504/b9dc49b2-4526-11e7-8aa5-d79cd3f6b4cb.png)

**Edit**: As a suggestion, it would seem to me that the simplest thing to do would be to check the error code and also handle that:

```javascript
fs.stat(fullPath(filepath, options), (err, stats) => {
  if (err) {
    return err.code === "ENOENT" ?
      false :
      done(err)
  }

  done(null, stats.isFile())
})
```

I'll try to make a PR when I can..
